name: build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          cache: "maven"
      - run: cd tests && mvn clean test --batch-mode -Dmaven.test.failure.ignore=true
      - uses: scacap/action-surefire-report@master
        if: endsWith(github.ref, 'master') == false
        with:
          check_name: Example Surefire Test Report
      - uses: cclauss/GitHub-Action-for-pytest@0.5.0
        with:
          args: pytest  --junit-xml=python/report.xml python/ || exit 0
      - uses: scacap/action-surefire-report@master
        if: endsWith(github.ref, 'master') == false
        with:
          check_name: Example Pytest Report
          report_paths: python/report.xml
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - run: npm run eslint
      - run: npm run test
